[project]
name = "the-black-goat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "absurd-sdk>=0.3.0",
    "croniter>=6.2.2",
    "dspy>=3.2.0",
    "fastapi>=0.136.1",
    "fastmcp>=3.2.4",
    "pluggy>=1.6.0",
    "pydantic>=2.13.3",
]

[project.scripts]
the-black-goat = "the_black_goat:main"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "absurdctl>=0.3.0",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "the-black-goat-stdlib",
    "the-black-goat-memory",
]

[tool.uv.workspace]
members = ["the-thousand-young/*"]

[tool.uv.sources]
the-black-goat-stdlib = { workspace = true }
the-black-goat-memory = { workspace = true }
